name: Update JSON from Google Sheet

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download sheet data
        run: |
          curl "https://opensheet.elk.sh/1MMroigh5CcNq-llBXa4BmPnJgG9sX5Pyhqj-Icmu7WU/Sheet1" -o data.json

      - name: Commit update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update artifact data" || exit 0
          git push
